name: Tencode
main: net.castegaming.plugins.tencode
version: 0.1
description: Tencode plugin
authors: [kwek20]
commands:
  cmd:
    description: cmd command
    usage: Type /cmd 
    aliases: [cmd1]
    
permissions:
  tencode.*:
    description: Gives access to all plugin commands
    children:
     name.reload: true
  tencode.reload: 
    description: Allows you to reload the plugin