name: visionist
main: net.castegaming.plugins.visionist
version: 0.1
description: Visionist plugin
authors: [kwek20]
commands:
  visionist:
    description: visionist base command
    usage: Type /visionist to see the info 
    aliases: [v]
    
permissions:
  visionist.*:
    description: Gives access to all plugin commands
    children:
     name.reload: true
  visionist.reload: 
    description: Allows you to reload the plugin