name: visionist
main: net.castegaming.plugins.visionist.Visionist
version: 0.1
description: Visionist plugin
authors: [kwek20]
commands:
  visionist:
    description: visionist base command
    usage: Type /visionist to see the info 
    aliases: [v]
  createstream:
    description: Create a stream of falling blocks at your location.
    usage: Type /createstream [MATERIAL] [amount] [byte] to create a stream at your location. last 2 optional.
    aliases: [cs, creates, cstream] 
  disablestream:
    description: Disables the stream nearest to you
    usage: Type /disablestream to disable the stream nearest to you
    aliases: [ds, disables, dstream] 
  enablestream:
    description: Enables the stream nearest to you
    usage: Type /enablestream to disable the stream nearest to you
    aliases: [ss, enables, estream] 
  removestream:
    description: Removes the stream nearest to you
    usage: Type /removestream to remove the stream nearest to you
    aliases: [rs, removes, rstream] 
    
    
permissions:
  visionist.*:
    description: Gives access to all plugin commands
    children:
     name.reload: true
  visionist.reload: 
    description: Allows you to reload the plugin